language: node_js
node_js: 
- 0.10
notifications:
- fernandosilvarosa@ymail.com
before_install:
- npm install -g bower@1.3
- npm install -g grunt-cli@0.1
- npm install -g karma-cli@0.0
- npm install -g protractor@1.5
- webdriver-manager update
- bower install
before_script:
- npm install --save-dev karma-phantomjs-launcher@0.1
- grunt
- cd  dist
- node server &
- sleep 10
script:
- karma start config/karma.config.js --single-run --browsers PhantomJS